{% set name = "excitingtools" %}
{% set version = "1.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/excitingtools-{{ version }}.tar.gz
  sha256: 24e17811d44bf830c396b872a76e373534c9499f8098aeaeb98d6e0a4aa9d76f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=35.0.2
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.20.0
    - matplotlib-base >=2.2.0

test:
  imports:
    - excitingtools
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/exciting/excitingtools
  summary: Utilities for aiding in the construction of exciting inputs and the postprocessing exciting outputs.
  license: LGPL-3.0-only
  license_file:
    - COPYING.LESSER
    - COPYING.md

extra:
  recipe-maintainers:
    - AlexBuccheri
    - jan-janssen
