{% set name = "excitingtools" %}
{% set version = "1.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/excitingtools-{{ version }}.tar.gz
  sha256: b10ba16c25a48a3610532e986de1e0710bcb204b8ec1dcd0fa7ac1478befb0f2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - setuptools >=35.0.2
    - setuptools-scm >=3.5.0
    - pip
  run:
    - python >=3.6
    - wheel >=0.35.0
    - numpy >=1.14.5
    - matplotlib-base >=2.2.0

test:
  imports:
    - excitingtools
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/exciting/excitingtools
  summary: Utilities for aiding in the construction of exciting inputs and the postprocessing exciting outputs.
  license: LGPL-3.0-only
  license_file:
    - COPYING.LESSER
    - COPYING.md

extra:
  recipe-maintainers:
    - AlexBuccheri
